image: ruby1.9.3
script:
  - bundle install
  - bundle exec appraisal install
  - bundle exec appraisal rake
notify:
  email:
    recipients:
      - drone@clever.com
  hipchat:
    room: Clever-Dev-CI
    token: {{hipchatToken}}
    on_started: true
    on_success: true
    on_failure: true
