=begin
#Clever API

#The Clever API

OpenAPI spec version: 1.2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CleverAPI::DistrictObject
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DistrictObject' do
  before do
    # run before each test
    @instance = CleverAPI::DistrictObject.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DistrictObject' do
    it 'should create an instact of DistrictObject' do
      expect(@instance).to be_instance_of(CleverAPI::DistrictObject)
    end
  end
  describe 'test attribute "object"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

