=begin
#Clever API

#The Clever API

OpenAPI spec version: 1.2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CleverAPI::StudentcontactsDeleted
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StudentcontactsDeleted' do
  before do
    # run before each test
    @instance = CleverAPI::StudentcontactsDeleted.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StudentcontactsDeleted' do
    it 'should create an instact of StudentcontactsDeleted' do
      expect(@instance).to be_instance_of(CleverAPI::StudentcontactsDeleted)
    end
  end
  describe 'test attribute "type"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

