=begin
#Clever API

#The Clever API

OpenAPI spec version: 1.2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

# Common files
require 'clever-api/api_client'
require 'clever-api/api_error'
require 'clever-api/version'
require 'clever-api/configuration'

# Models
require 'clever-api/models/bad_request'
require 'clever-api/models/district'
require 'clever-api/models/district_admin'
require 'clever-api/models/district_admin_response'
require 'clever-api/models/district_admins_response'
require 'clever-api/models/district_object'
require 'clever-api/models/district_response'
require 'clever-api/models/district_status'
require 'clever-api/models/district_status_response'
require 'clever-api/models/districts_created'
require 'clever-api/models/districts_deleted'
require 'clever-api/models/districts_response'
require 'clever-api/models/districts_updated'
require 'clever-api/models/event'
require 'clever-api/models/event_response'
require 'clever-api/models/events_response'
require 'clever-api/models/grade_levels_response'
require 'clever-api/models/internal_error'
require 'clever-api/models/location'
require 'clever-api/models/name'
require 'clever-api/models/not_found'
require 'clever-api/models/principal'
require 'clever-api/models/school'
require 'clever-api/models/school_admin'
require 'clever-api/models/school_admin_object'
require 'clever-api/models/school_admin_response'
require 'clever-api/models/school_admins_response'
require 'clever-api/models/school_object'
require 'clever-api/models/school_response'
require 'clever-api/models/schooladmins_created'
require 'clever-api/models/schooladmins_deleted'
require 'clever-api/models/schooladmins_updated'
require 'clever-api/models/schools_created'
require 'clever-api/models/schools_deleted'
require 'clever-api/models/schools_response'
require 'clever-api/models/schools_updated'
require 'clever-api/models/section'
require 'clever-api/models/section_object'
require 'clever-api/models/section_response'
require 'clever-api/models/sections_created'
require 'clever-api/models/sections_deleted'
require 'clever-api/models/sections_response'
require 'clever-api/models/sections_updated'
require 'clever-api/models/student'
require 'clever-api/models/student_contact'
require 'clever-api/models/student_contact_object'
require 'clever-api/models/student_contact_response'
require 'clever-api/models/student_contacts_response'
require 'clever-api/models/student_object'
require 'clever-api/models/student_response'
require 'clever-api/models/studentcontacts_created'
require 'clever-api/models/studentcontacts_deleted'
require 'clever-api/models/studentcontacts_updated'
require 'clever-api/models/students_created'
require 'clever-api/models/students_deleted'
require 'clever-api/models/students_response'
require 'clever-api/models/students_updated'
require 'clever-api/models/teacher'
require 'clever-api/models/teacher_object'
require 'clever-api/models/teacher_response'
require 'clever-api/models/teachers_created'
require 'clever-api/models/teachers_deleted'
require 'clever-api/models/teachers_response'
require 'clever-api/models/teachers_updated'
require 'clever-api/models/term'

# APIs
require 'clever-api/api/default_api'

module CleverAPI
  class << self
    # Customize default settings for the SDK using block.
    #   CleverAPI.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
