=begin
#Clever API

#The Clever API

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

module Clever
  VERSION = "2.0.2"
end
